### ISSUE TITLE
The lowering of the thresholds creates a ton of false flags.

### ISSUE THREAD

**Issue by ccuser44** [Hexcede/Hexolus-Anticheat#7]
Spesifically it is the teleportation that misdetects the most of the time.
I think the current way of setting back the player is via teleportation. However this isn't ideal as the problem isn't how much they can change their position in one instant but how much total distance they can gain. The current method of distance gain detection relies on having the teleportation checks really low so it can limit the distance gained. However this is undesired and does cause a lot of false flags. For example 2 studs isn't really a lot and I wouldn't really consider it teleporting. How it should in my opinion work is that the teleportation distance would be risen to much higher and that there would be a check where it would check for example how much total distance is a player gaining and if it is too much teleport them back to a desired position.

**Comment by Hexcede** [comment]
The problem primarily with this is how to measure "gained distance." Without a reference point I have no way to measure the distance gained.

Say, for example, the threshold is raised to 5 studs per second. The player might teleport 5 studs, wait 1 second (~60 frames), teleport 5 studs again, etc, etc. How can I know when to assume the player is no longer "gaining" distance? I would have to mark some start position, currently this is per frame, and then I would have to decide when to unmark that position. There doesn't seem to me to be a good way to do this.

The best solution I can come up with is to give a time frame parameter, e.g. 5 seconds. I can then say that, if the player has moved a total of X studs more than expected in that time frame, I lag them back. This is probably what I will end up doing, but, it most likely won't solve the issue.

Additionally, can you describe to me exactly how these false positives are occurring for you, and what impact they are having? Is this occurring due to network lag, for example? Is it noticeable to you as a player, e.g. is the prediction off enough to be annoying? My concern is not around whether false positives exist, false positives will always exist and I expect them to be frequent. My concern is mostly around the impact this will have on players vs the freedom it will give exploiters. False positives are only a concern to me if they annoy or detriment the player in some way, this is a benefit of my methodology on how I create my anticheat.

**Comment by Hexcede** [comment]
I've raised the thresholds again based on testing, hopefully this should be better.
I will be implementing a better prediction system and modularizing the anticheat in the next major update.

**Comment by ccuser44** [comment]
The jumping was the thing that false flagged the most was jumping. (Vertical teleportation) For me it detected jumping too often preventing me from jumping 40% of the time. I am not sure if they are fixed as I cannot test them right now.

**Comment by Hexcede** [comment]
> The jumping was the thing that false flagged the most was jumping. (Vertical teleportation) For me it detected jumping too often preventing me from jumping 40% of the time. I am not sure if they are fixed as I cannot test them right now.

Hmm. I raised the vertical threshold. I haven't had any issues with it myself interestingly. Next time you get a chance let me know if you are still having similar issues. Ideally, there wouldn't be false positives, but there is no way to eliminate them entirely without defeating the purpose of the anticheat. 

What _should_ happen in the case of false positives is that you should be able to jump you might just get a slight stutter, it shouldn't be enough to be impactful.

**Comment by ccuser44** [comment]
Seems like this is fixed
