### ISSUE TITLE
Anti exploit doesn't detect vertical speed accurately if body velocity is used even on the client

### ISSUE THREAD

**Issue by angrybino** [Hexcede/Hexolus-Anticheat#9]
The anti exploit doesn't detect vertical speed accurately if body velocity is used even on the client, which is a flaw since exploiters can easily bypass the vertical speed check.

**Comment by Hexcede** [comment]
> The anti exploit doesn't detect vertical speed accurately if body velocity is used even on the client, which is a flaw since exploiters can easily bypass the vertical speed check.

BodyVelocity isn't any different than setting the Velocity of the root part of an assembly on Heartbeat so there is no reason for BodyVelocity to bypass the vertical speed check. Are you sure the velocity is actually high enough to be detected in the first place?

This may just be due to a bug with the way the limits are calculated for the check, there isn't any reason this vs anything else would get around the check. It should be calculated based on the mass of the player's assembly and the current gravity and it may be that I didn't do my math correctly there.

**Comment by angrybino** [comment]
IIRC, It doesn't matter if it was, since it checks if the player is on the ground or not for a certain amount of time, the player was still on the air for a long amount of time.

**Comment by Hexcede** [comment]
> IIRC, It doesn't matter if it was, since it checks if the player is on the ground or not for a certain amount of time, the player was still on the air for a long amount of time.

This is the flight check, not the vertical speed check, which, is disabled by default due to it being unstable. The vertical speed check calculates a maximum upwards speed for a player based on the gravity and the player's JumpPower. The downwards speed is boundless due to gravity. The player will only trigger the vertical speed check if traveling upwards faster than is calculated to be allowed.

The vertical speed check is just meant to prevent players from traveling upwards faster than they should be allowed to, its not meant to prevent them from gaining height at all. (E.g. by traveling upwards slower than the threshold) That would be caught by the flight check, which, as I mentioned currently isn't stable enough so its disabled by default. It's on my TODO list as a priority to implement a new flight check, but I have other things in my game that precede it right now and its a fairly large task being the most complex & difficult check in the AC.

I also wasn't able to reproduce an issue at all when testing, everything seems fine to me so I assume this is was a misinterpretation.

**Comment by SilentsReplacement** [comment]
Right
